---
driver:
  name: hyperv
  memory_startup_bytes: 1073741824
  password: 'vagrant'

transport:
  name: winrm

verifier:
  name: pester

provisioner:
  name: shell
  driver:
    parent_vhd: 'C:\VHD\Ref_W12R2EN_unattend.vhdx'

platforms:
  - name: windows_2012r2

suites:
  - name: default
